# Generated by Django 4.2 on 2023-07-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('funcao_exercida', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('password', models.CharField(editable=False, max_length=50)),
                ('area_interesse', models.CharField(choices=[('c', 'Contabilidade'), ('p', 'Plantio'), ('l', 'Colheita'), ('d', 'Distribuição'), ('i', 'Insumos')], max_length=1, null=True)),
            ],
        ),
    ]
