# Generated by Django 4.2 on 2023-07-30 04:06

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14),
        ),
    ]
