# Generated by Django 4.2 on 2023-07-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_funcionario_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Insira números válidos'}, max_digits=8),
        ),
    ]
