# Generated by Django 4.2 on 2023-08-01 16:27

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_funcionario_area_interesse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Inicio')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('motivo', models.CharField(max_length=500, verbose_name='Motivo')),
            ],
        ),
    ]
