# Generated by Django 4.2 on 2023-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gerenciafolga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciafolga',
            name='data_inicio',
            field=models.DateField(auto_now=True, verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='gerenciafolga',
            name='motivo',
            field=models.TextField(max_length=500, verbose_name='Motivo'),
        ),
    ]
