# Generated by Django 4.2 on 2023-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_gerenciafolga_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciafolga',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Inicio'),
        ),
    ]
