# Generated by Django 4.2 on 2023-08-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_gerenciafolga_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(editable=False, max_length=50, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Salário'),
        ),
    ]
