# Generated by Django 4.2 on 2023-08-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_funcionario_password_alter_funcionario_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Senha'),
        ),
    ]
