# Generated by Django 4.2 on 2023-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_funcionario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciafolga',
            name='selectmotivo',
            field=models.CharField(choices=[('F', 'Falecimento de cônjuge'), ('C', 'Licença de Casamento'), ('N', 'Nascimento de Filho'), ('D', 'Doação de Sangue Voluntária'), ('A', 'Alistamento Eleitoral'), ('S', 'Serviço Militar'), ('V', 'Vestibular'), ('M', 'Acompanhamento Médico'), ('E', 'Exames/Consultas Preventivas de Câncer'), ('O', 'Problemas de Saúde'), ('R', 'Reunião em organismo internacional')], max_length=1, null=True, verbose_name='Tipos de Licença'),
        ),
    ]
