# Generated by Django 4.2 on 2023-08-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_gerenciafolga_selectmotivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciafolga',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='gerenciafolga',
            name='data_termino',
        ),
    ]
