# Generated by Django 4.2 on 2023-08-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_funcionario_status_folga_gerenciafolga_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciafolga',
            name='funcionario',
        ),
    ]
