# Generated by Django 4.2 on 2023-08-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_funcionario_status_folga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciafolga',
            name='motivo',
            field=models.TextField(blank=True, max_length=500, verbose_name='Motivo'),
        ),
    ]
